services:
  api:
    container_name: sampleckwebapp-api
    build:
      context: ../..
      dockerfile: docker/build/SampleCkWebApp.Dockerfile
    ports:
      - "8080:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      Database__ConnectionString:   "Host=db;Port=5432;Database=expense_tracker;Username=sampleuser;Password=samplepass"
    depends_on:
      - db

  db:
    container_name: sampleckwebapp-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: "expense_tracker"
      POSTGRES_USER: "sampleuser"
      POSTGRES_PASSWORD: "samplepass"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

